#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp-sbfe-flash

COMPONENTS := esptool_py esp-sbfe/esp-sbfe-flash

IS_BOOTLOADER_BUILD := 1
export IS_BOOTLOADER_BUILD

include $(IDF_PATH)/make/project.mk

