# ESP32 Secure Boot & Flash Encryption target
#
# extends the ESP IDF to handle flashing and reflashing devices with secure boot
# and flash encryption enabled dynamically
#

include $(wildcard $(COMPONENT_PATH)/sbfe_*.mk)

sbfe-pjr:
	echo $(FLH_FW_DEP)
	echo $(FLH_FW_ARGS)

sbfe-flash-app:
	echo "Target to flash app with SBFE support"


