
FLH_FW_SBFE_BIN_DIR:=$(BUILD_DIR_BASE)/$(notdir $(COMPONENT_PATH))

FLH_FW_BOOTLOADER_BIN_DIGST=$(FLH_FW_SBFE_BIN_DIR)/fw_bootloader_digest.bin

FLH_FW_BOOTLOADER_BIN_ENC=$(FLH_FW_SBFE_BIN_DIR)/fw_bootloader_enc.bin

FLH_FW_BOOTLOADER_BIN_DIGST_ENC=$(FLH_FW_SBFE_BIN_DIR)/fw_bootloader_digest_enc.bin

# Starts with nothing
FLH_FW_SBFE_BOOTLOADER_BIN=
# Starts with default
FW_SBFE_BOOTLOADER_OFFSET=$(FW_PKG_BOOTLOADER_OFFSET)

ifeq ($(SBFE_VAR_SECURE_BOOT),1)

FW_SBFE_BOOTLOADER_OFFSET=0
FLH_FW_SBFE_BOOTLOADER_BIN=$(FLH_FW_BOOTLOADER_BIN_DIGST)

.SECONDEXPANSION:
$(FLH_FW_BOOTLOADER_BIN_DIGST): $$(FW_BOOTLOADER_BIN) $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_SB_KEY_FILENAME)
	echo "Generating Bootloader Digest"
	echo "Secure Boot Hardware Key : $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_SB_KEY_FILENAME)"
	$(ESPSECUREPY) digest_secure_bootloader \
					-k $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_SB_KEY_FILENAME) \
					-o $@ $<

.INTERMEDIATE: $(FLH_FW_BOOTLOADER_BIN_DIGST)

endif

ifeq ($(SBFE_VAR_FLASH_ENCRYPTION),1)

FLH_FW_SBFE_BOOTLOADER_BIN_DEP:=$(if $(FLH_FW_SBFE_BOOTLOADER_BIN),$(FLH_FW_BOOTLOADER_BIN_DIGST),$(FW_BOOTLOADER_BIN))
FLH_FW_SBFE_BOOTLOADER_BIN:=$(if $(FLH_FW_SBFE_BOOTLOADER_BIN),$(FLH_FW_BOOTLOADER_BIN_DIGST_ENC),$(FLH_FW_BOOTLOADER_BIN_ENC))

.SECONDEXPANSION:
$(FLH_FW_SBFE_BOOTLOADER_BIN): $$(FLH_FW_SBFE_BOOTLOADER_BIN_DEP) $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_FE_KEY_FILENAME)
	echo "Generating $@"
	echo "Flash Encyption Hardware Key : $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_FE_KEY_FILENAME)"
	$(ESPSECUREPY) encrypt_flash_data \
			-k $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_FE_KEY_FILENAME) \
			-a $(FW_SBFE_BOOTLOADER_OFFSET) -o $@ $<

endif

FLH_FW_DEP+=$(if $(FLH_FW_SBFE_BOOTLOADER_BIN),$(FLH_FW_SBFE_BOOTLOADER_BIN))
FLH_FW_ARGS+=$(if $(FLH_FW_SBFE_BOOTLOADER_BIN),$(FW_SBFE_BOOTLOADER_OFFSET) $(FLH_FW_SBFE_BOOTLOADER_BIN))

