FLH_FW_SBFE_BIN_DIR:=$(BUILD_DIR_BASE)/$(notdir $(COMPONENT_PATH))

FLH_FW_PARTTABLE_BIN_ENC=$(FLH_FW_SBFE_BIN_DIR)/fw_parttable_encrypted.bin

# Firmware and Partition Table
ifeq ($(SBFE_VAR_FLASH_ENCRYPTION),1)
FLH_FW_DEP+=$(FLH_FW_PARTTABLE_BIN_ENC)
FLH_FW_ARGS+=$(FW_PKG_PARTTABLE_OFFSET) $(FLH_FW_PARTTABLE_BIN_ENC)
else
FLH_FW_DEP+=$(FW_PARTTABLE_BIN)
FLH_FW_ARGS+=$(FW_PKG_PARTTABLE_OFFSET) $(FW_PARTTABLE_BIN)
endif

$(FLH_FW_PARTTABLE_BIN_ENC): $$(FW_PARTTABLE_BIN) $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_FE_KEY_FILENAME)
	echo "Generating $@ from $<"
	$(ESPSECUREPY) encrypt_flash_data \
			-k $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_FE_KEY_FILENAME) \
			-a $(FW_PKG_PARTTABLE_OFFSET) -o $@ $<