FLH_FW_SBFE_BIN_DIR:=$(BUILD_DIR_BASE)/$(notdir $(COMPONENT_PATH))

FLH_DEV_NVS_KEY0_FILE_ENC=$(FLH_FW_SBFE_BIN_DIR)/dev_nvs_key0_encrypted.bin
FLH_DEV_NVS_KEY1_FILE_ENC=$(FLH_FW_SBFE_BIN_DIR)/dev_nvs_key1_encrypted.bin
# NVS Key and Data

ifeq ($(SBFE_VAR_FLASH_ENCRYPTION),1)
FLH_FW_DEP+=$(FLH_DEV_NVS_KEY0_FILE_ENC) $(FLH_DEV_NVS_KEY1_FILE_ENC)
FLH_FW_ARGS+=$(FW_PKG_NVS_KEY0_OFFSET) $(FLH_DEV_NVS_KEY0_FILE_ENC)
FLH_FW_ARGS+=$(FW_PKG_NVS_KEY1_OFFSET) $(FLH_DEV_NVS_KEY1_FILE_ENC)
FLH_FW_ARGS+=$(FW_PKG_NVS0_OFFSET) $(FLH_DEV_NVS_FILE)
FLH_FW_ARGS+=$(FW_PKG_NVS1_OFFSET) $(FLH_DEV_NVS_FILE)
endif

# dev-prov provides the FLH_DEV_NVS_FILE and FLH_DEV_NVS_KEY_FILE
$(FLH_DEV_NVS_KEY0_FILE_ENC): dev-prov $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_FE_KEY_FILENAME)
	echo "Generating $@ from $(FLH_DEV_NVS_KEY_FILE)"
	$(ESPSECUREPY) encrypt_flash_data \
			-k $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_FE_KEY_FILENAME) \
			-a $(FW_PKG_NVS_KEY0_OFFSET) -o $@ $(FLH_DEV_NVS_KEY_FILE)

$(FLH_DEV_NVS_KEY1_FILE_ENC): dev-prov $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_FE_KEY_FILENAME)
	echo "Generating $@ from $(FLH_DEV_NVS_KEY_FILE)"
	$(ESPSECUREPY) encrypt_flash_data \
			-k $(SBFE_VAR_KEY_DIR)/$(SBFE_VAR_FE_KEY_FILENAME) \
			-a $(FW_PKG_NVS_KEY1_OFFSET) -o $@ $(FLH_DEV_NVS_KEY_FILE)